tpc_ds_benchmark:
  target: databricks_job
  outputs:
    databricks_job:
    type: databricks
    method: http
    schema: "tfayyaz_demo"
    host: "{{ env_var('DBT_CLUSTER_HTTP_HOST') }}"
    http_path: "{{ env_var('DBT_CLUSTER_HTTP_PATH') }}"
    token: "{{ env_var('DBT_ACCESS_TOKEN') }}"